name: budget_tracker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.0

  gap: ^3.0.1
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  font_awesome_flutter: ^10.8.0

  go_router: ^16.0.0

  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1

  dio: ^5.8.0+1

  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
    - assets/svg/
